stages:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: python-app:latest

test:
  stage: test
  image: python:3.10
  script:
    - pip install --cache-dir=.pip_cache -r app/requirements.txt
    - python -m unittest discover app/tests/

build:
  stage: build
  image: docker:20.10.7
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE app/
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_IMAGE

deploy:
  stage: deploy
  image: bitnami/kubectl
  script:
    - echo "$KUBECONFIG_CONTENT" > kubeconfig
    - export KUBECONFIG=$(pwd)/kubeconfig
    - kubectl apply -f k8s/deployment.yaml
    - kubectl apply -f k8s/service.yaml
  only:
    - main
